# Generated by Django 4.2.20 on 2025-10-10 10:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BakalavrYunalishlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shifr', models.CharField(max_length=20)),
                ('yunalish_nomi', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': "yo'nalish",
                'verbose_name_plural': "yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='kategoriya')),
                ('slug', models.SlugField(default='')),
                ('icon', models.ImageField(null=True, upload_to='images')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, verbose_name='Til')),
            ],
            options={
                'verbose_name': 'Til',
                'verbose_name_plural': 'Tillar',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, verbose_name='Resurs turi')),
            ],
            options={
                'verbose_name': 'Resurs turi',
                'verbose_name_plural': 'Resurslar turi',
            },
        ),
        migrations.CreateModel(
            name='UqitiladiganFanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'fan',
                'verbose_name_plural': 'fanlar',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='resources/', verbose_name='Rasm')),
                ('original_file', models.FileField(upload_to='pdfs/originals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fayl yuklash')),
                ('watermarked_file', models.FileField(blank=True, null=True, upload_to='pdfs/watermarkeds/')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mamlakat')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yil')),
                ('direction', models.CharField(blank=True, max_length=100, null=True, verbose_name="Yo'nalish")),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sahifalar soni')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name="Kalit so'zlar")),
                ('auditoria', models.CharField(choices=[('all', 'Barcha uchun'), ('students', "O'quvchilar uchun"), ('teachers', "O'qituvchilar uchun")], default='all', max_length=30, verbose_name='Ruxsat')),
                ('status', models.CharField(choices=[('free', 'Bepul'), ('partial', 'Qisman ochiq'), ('premium', 'Premium')], default='free', max_length=30, verbose_name='Holat')),
                ('slug', models.SlugField(default='')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.category')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.language', verbose_name='Til')),
                ('resource_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resurslar', to='resources.resourcetype', verbose_name='Resurs turi')),
            ],
            options={
                'verbose_name': 'Resurs',
                'verbose_name_plural': 'Resurslar',
            },
        ),
    ]
