# Generated by Django 4.2.20 on 2025-10-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_contact_alter_favourite_unique_together_and_more'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='language',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ResourceType',
        ),
    ]
