# Generated by Django 4.2.20 on 2025-11-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_category_remove_resource_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlmiyYangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('created_at', models.TimeField(auto_now=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ilmiy_yangilik',
                'verbose_name_plural': 'ilmiy_yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='XalqaroHamkorliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('created_at', models.TimeField(auto_now=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'xalqaro hamkorlik',
                'verbose_name_plural': 'xalqaro hamkorliklar',
            },
        ),
        migrations.CreateModel(
            name='XalqaroHamkorliklarRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ilmiy_yangiliklar/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('yangilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='resources.xalqarohamkorliklar')),
            ],
        ),
        migrations.CreateModel(
            name='IlmiyYangilikRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ilmiy_yangiliklar/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('yangilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='resources.ilmiyyangiliklar')),
            ],
        ),
    ]
