# Generated by Django 4.2.20 on 2025-10-10 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Elonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='elonlar/', verbose_name="e'lonlar")),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('data', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': "e'lon",
                'verbose_name_plural': "e'lonlar",
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('talim_shakli', models.CharField(choices=[('kunduzgi', 'kunduzgi'), ('sirtqi', 'sirtqi'), ('masofaviy', 'masofaviy')], max_length=20)),
                ('course', models.CharField(choices=[('1', '1-kurs'), ('2', '2-kurs'), ('3', '3-kurs'), ('4', '4-kurs'), ('5', '5-kurs')], max_length=10)),
            ],
            options={
                'verbose_name': 'fan',
                'verbose_name_plural': 'fanlar',
            },
        ),
        migrations.CreateModel(
            name='MeyoriyHujjat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('file_link', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'meyoriy hujjat',
                'verbose_name_plural': 'meyoriy hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='xodimlar/', verbose_name='xodimning_rasmi')),
                ('ism', models.CharField(max_length=50)),
                ('familiya', models.CharField(max_length=50)),
                ('otchestva', models.CharField(max_length=50)),
                ('lavozim', models.CharField(max_length=50)),
                ('ilmiy_daraja', models.CharField(max_length=500)),
                ('ilmiy_unvon', models.CharField(max_length=500)),
                ('qabul_kunlar', models.CharField(max_length=100)),
                ('manzil', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mehnat_faoliyati', models.TextField()),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('google_scholar', models.CharField(blank=True, max_length=500, null=True)),
                ('scopus', models.CharField(blank=True, max_length=500, null=True)),
                ('researchgate', models.CharField(blank=True, max_length=500, null=True)),
                ('orcid', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
                ('telegram', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube', models.CharField(blank=True, max_length=500, null=True)),
                ('shaxsiysayt', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='yangiliklar/', verbose_name='yangilik')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'yangilik',
                'verbose_name_plural': 'yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Videodarslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=5)),
                ('pdf_nomi', models.CharField(blank=True, max_length=500, null=True)),
                ('document_link', models.TextField()),
                ('authors', models.ManyToManyField(blank=True, related_name='videodarslik', to='home.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UslubiyNashr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.CharField(max_length=5)),
                ('pdf_nomi', models.CharField(blank=True, max_length=500, null=True)),
                ('document_link', models.TextField()),
                ('extra_authors', models.TextField(blank=True, help_text="Yana boshqa Mualliflar mavjud bo'lsa, qo'lda kiriting:", null=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='uslubiy_nashrlar', to='home.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.CharField(max_length=5)),
                ('pdf_nomi', models.CharField(blank=True, max_length=500, null=True)),
                ('document_link', models.TextField()),
                ('authors', models.ManyToManyField(blank=True, related_name='sertificate', to='home.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loyiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.CharField(max_length=5)),
                ('pdf_nomi', models.CharField(blank=True, max_length=500, null=True)),
                ('document_link', models.TextField()),
                ('authors', models.ManyToManyField(blank=True, related_name='loyiha', to='home.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IlmiyNashr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.CharField(max_length=5)),
                ('pdf_nomi', models.CharField(blank=True, max_length=500, null=True)),
                ('document_link', models.TextField()),
                ('extra_authors', models.TextField(blank=True, help_text="Yana boshqa Mualliflar mavjud bo'lsa, qo'lda kiriting:", null=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='ilmiy_nashrlar', to='home.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fan_tarkibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('file_link', models.CharField(max_length=1000)),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_tarkibi', to='home.fan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fan',
            name='meyoriy_hujjat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan', to='home.meyoriyhujjat'),
        ),
        migrations.CreateModel(
            name='AvtoReferat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.CharField(max_length=5)),
                ('pdf_nomi', models.CharField(blank=True, max_length=500, null=True)),
                ('document_link', models.TextField()),
                ('extra_authors', models.TextField(blank=True, help_text="Yana boshqa Mualliflar mavjud bo'lsa, qo'lda kiriting:", null=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='avtoreferat', to='home.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
