# Generated by Django 4.2.20 on 2025-10-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fan/'),
        ),
    ]
