# Generated by Django 4.2.20 on 2025-12-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ilmiynashr',
            old_name='pdf_nomi',
            new_name='jurnal_nomi',
        ),
        migrations.RemoveField(
            model_name='loyiha',
            name='pdf_nomi',
        ),
        migrations.RemoveField(
            model_name='videodarslik',
            name='pdf_nomi',
        ),
        migrations.AddField(
            model_name='ilmiynashr',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ilmiynashr',
            name='sahifalar_soni',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
