# Generated by Django 4.2.20 on 2025-10-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fan_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adabiyotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_name', models.CharField(max_length=1000)),
                ('file_link', models.CharField(max_length=1000)),
                ('specific_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adabiyotlar', to='home.fan')),
            ],
            options={
                'verbose_name': 'adabiyot',
                'verbose_name_plural': 'adabiyotlar',
            },
        ),
    ]
