# Generated by Django 4.2.20 on 2025-10-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_adabiyotlar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
