# Generated by Django 4.2.20 on 2025-10-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_contact_alter_favourite_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
