# Generated by Django 4.2.20 on 2025-10-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_yangiliklar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='elonlar',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
