# Generated by Django 4.2.20 on 2025-10-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_elonlar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
