# Generated by Django 4.2.20 on 2025-10-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_adabiyotlar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='ilmiy_daraja',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='ilmiy_unvon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='qabul_kunlar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
