# Generated by Django 4.2.20 on 2025-10-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_worker_ilmiy_daraja_alter_worker_ilmiy_unvon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sertifikatlar/', verbose_name='sertificate'),
        ),
    ]
